# Generated by Django 6.0.4 on 2026-04-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('market_cap_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ranking (Market Cap)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Link do ikony')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Kryptowaluta',
                'verbose_name_plural': 'Kryptowaluty',
            },
        ),
        migrations.DeleteModel(
            name='UserWatchlist',
        ),
    ]
